language: php
php:
  - '7.1'
sudo: required
dist: trusty
group: edge

env:
  global:
  - REPO=thulana/orangehrmos
  - TAG=develop

services:
  - mysql
  - docker

before_install: ./travis-cofig-files/test/before_install.sh
before_script: ./travis-cofig-files/test/before_script.sh
  
after_failure: ./travis-cofig-files/test/after_failure.sh
install: ./travis-cofig-files/test/install.sh

notifications:
  email: true
  
jobs:
  include:
    - stage: test
      script: ./travis-cofig-files/test/script.sh
    - stage: deploy
      env:
      before_install: skip
      install: skip
      before_script: ./travis-cofig-files/docker/before_script.sh
      script: ./travis-cofig-files/docker/script.sh
      after_script: ./travis-cofig-files/docker/after_script.sh 
    - stage: deploy
      env:
      before_install: skip
      install: skip
      before_script: ./travis-cofig-files/heroku/before_script.sh
      script: ./travis-cofig-files/heroku/script.sh
        

