language: php
php:
  - '7.1'
sudo: required
dist: trusty
group: edge

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini
  - uname -a
  - php --version
  - phpunit --version
  - mysqladmin -uroot status
  - composer self-update
  - sudo chmod 777 -R symfony/cache
  - sudo chmod 777 -R symfony/log
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
install:
  - composer install -d symfony/lib
  - composer dump-autoload -o -d symfony/lib
  - php installer/cli_install.php 0
  - php devTools/general/create-test-db.php root
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - echo "Download selenium-server-standalone jar file"
  - wget -c -nc --retry-connrefused --tries=0 http://goo.gl/EoH85x -O selenium-server-standalone.jar
  - echo "Run selenium server - background process"
  - nohup bash -c "java -jar selenium-server-standalone.jar &" && sleep 1; cat nohup.out
  - echo "Run php in-built server - background process"
  - nohup bash -c "php -S localhost:8000 2>&1 -t /symfony/web/ &" && sleep 1; cat nohup.out
  
script:
  - symfony/lib/vendor/bin/phpunit
  - php codecept.phar run acceptance

notifications:
  email: true
