language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
sudo: required

services:
  - mysql
 
matrix:
    include:
        - os: linux
          dist: trusty          

before_install:
  - uname -a
  - php --version
  - mysql -uroot -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root')"
  - composer self-update

install:
  - composer install -d symfony/lib
  - cd installer && sudo bash cli_install.sh && cd ../

script:
  - symfony/lib/vendor/bin/codecept run -c symfony/test/api/

notifications:
  email: false
