language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
sudo: required
 
matrix:
    include:
        - os: linux
          dist: trusty          

before_install:
  - uname -a
  - php --version
  - composer self-update

install:
  - composer install -d symfony/lib

script:
  - symfony/lib/vendor/bin/codecept run -c symfony/test/api/
