language: php
php:
#  - '5.4'
#  - '5.5'
  - '5.6'
sudo: required

services:
  - mysql
  
matrix:
    include:
        - os: linux
          dist: trusty          

before_install:
  - uname -a
  - php --version
  - mysqladmin -uroot status
  - composer self-update
  - sudo chmod 777 -R symfony/cache
  - sudo chmod 777 -R symfony/log
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
install:
  - composer install -d symfony/lib
  - php installer/cli_install.php 0

#script:
#  - symfony/lib/vendor/bin/codecept run -c symfony/test/api/

notifications:
  email: true
