language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
sudo: required
 
matrix:
    include:
        - os: linux
          dist: trusty          

before_install:
  - uname -a
  - php --version
  
script:
  - phpunit symfony/test/PluginAllTests.php
