version: '2'
services:
  web:
    build: .
    command: 'bash -c ''vendor/bin/heroku-php-apache2 /app/public/'''
    environment:
      PORT: 8080
    ports:
      - '8080:8080'
# dev container
  dev:
    build: .
    ports:
      - "80:80"
