installer_home:
  path: /
  controller: OrangeHRM\Installer\Controller\HomeController::handle
  methods: [ GET ]

installer_welcome:
  path: /installer/welcome
  controller: OrangeHRM\Installer\Controller\WelcomeController::handle
  methods: [ GET ]

upgrader_database_config:
  path: /upgrader/database-config
  controller: OrangeHRM\Installer\Controller\Upgrader\DatabaseConfigController::handle
  methods: [ GET ]

##########################
#        APIs
##########################

api_upgrader_database_config:
  path: /upgrader/api/database-config
  controller: OrangeHRM\Installer\Controller\Upgrader\Api\DatabaseConfigAPI::handle
  methods: [ POST ]

api_upgrader_migration:
  path: /upgrader/api/migration
  controller: OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI::handle
  methods: [ GET, POST ]

api_upgrader_write_config:
  path: /upgrader/api/config-file
  controller: OrangeHRM\Installer\Controller\Upgrader\Api\ConfigFileAPI::handle
  methods: [ POST ]
