installer_home:
  path: /
  controller: OrangeHRM\Installer\Controller\HomeController::handle
  methods: [ GET ]

installer_welcome:
  path: /welcome
  controller: OrangeHRM\Installer\Controller\WelcomeController::handle
  methods: [ GET ]

upgrader_database_config:
  path: /upgrader/database-config
  controller: OrangeHRM\Installer\Controller\DatabaseConfigurationController::handle
  methods: [ GET ]

upgrader_system_check:
  path: /upgrader/system-check
  controller: OrangeHRM\Installer\Controller\SystemCheckController::handle
  methods: [ GET ]

upgrader_current_version:
  path: /upgrader/current-version
  controller: OrangeHRM\Installer\Controller\CurrentVersionDetailsController::handle
  methods: [ GET ]

upgrader_complete:
  path: /upgrader/complete
  controller: OrangeHRM\Installer\Controller\UpgraderCompleteController::handle
  methods: [ GET ]

##########################
#        APIs
##########################

api_upgrader_database_config:
  path: /upgrader/api/database-config
  controller: OrangeHRM\Installer\Controller\Upgrader\Api\DatabaseConfigAPI::handle
  methods: [ GET, POST ]

api_upgrader_migration:
  path: /upgrader/api/migration
  controller: OrangeHRM\Installer\Controller\Upgrader\Api\MigrationAPI::handle
  methods: [ GET, POST ]

api_upgrader_write_config:
  path: /upgrader/api/config-file
  controller: OrangeHRM\Installer\Controller\Upgrader\Api\ConfigFileAPI::handle
  methods: [ POST ]

api_upgrader_versions:
  path: /upgrader/api/versions
  controller: OrangeHRM\Installer\Controller\Upgrader\Api\VersionAPI::handle
  methods: [ GET ]

api_upgrader_current_version:
  path: /upgrader/api/current-version
  controller: OrangeHRM\Installer\Controller\Upgrader\Api\CurrentVersionAPI::handle
  methods: [ GET ]

api_system_check:
  path: /upgrader/api/system-check
  controller: OrangeHRM\Installer\Controller\Upgrader\Api\SystemCheckAPI::handle
  methods: [ GET ]
