name: Test

on:
  push:
    branches: [ '5.0' ]
  pull_request:
    branches: [ '5.0' ]

jobs:
  test:

    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Use composer v1
        run: sudo composer self-update --1

      - name: Validate composer.json and composer.lock
        run: |
          cd symfony
          composer validate --strict

      - name: Parse Git short hash
        run: echo "git_short_hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: Install depandancies
        run: |
          cd symfony
          php7.4 -f /usr/bin/composer install
          php7.4 -f /usr/bin/composer dump-autoload -o
          cd client
          yarn install

      - name: Install OrangeHRM
        run: |
          php installer/cli_install.php 0
          php devTools/general/create-test-db.php root

      - name: Run test
        run: |
          ./symfony/vendor/bin/phpunit

  composer_v2_check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: |
          cd symfony
          composer validate --strict

      - name: Install depandancies
        run: |
          cd symfony
          composer install
          composer dump-autoload -o
