database:
  hostName: mysql55
  hostPort: 3306
  databaseName: 52dev
  privilegedDatabaseUser: root
  privilegedDatabasePassword: root
  useSameDbUserForOrangeHRM: y # y/n, if this field `n` fill `orangehrmDatabaseUser` and `orangehrmDatabasePassword`
  orangehrmDatabaseUser: ~
  orangehrmDatabasePassword: ~
  isExistingDatabase: n # y/n
  enableDataEncryption: y # y/n

organization:
  name: OHRM
  country: US

admin:
  adminUserName: admin
  adminPassword: admin@OHRM123
  adminEmployeeFirstName: Devi
  adminEmployeeLastName: Admin
  workEmail: devi@admin.com
  contactNumber: ~

license:
  agree: y # y/n
