database:
  hostName: mariadb104
  hostPort: 3306
  databaseName: orangehrm_mysql_
  privilegedDatabaseUser: root
  privilegedDatabasePassword: root
  useSameDbUserForOrangeHRM: y # y/n, if this field `n` fill `orangehrmDatabaseUser` and `orangehrmDatabasePassword`
  orangehrmDatabaseUser: ~
  orangehrmDatabasePassword: ~
  isExistingDatabase: n # y/n

organization:
  name: OrangeHRM
  country: US

admin:
  adminUserName: Admin
  adminPassword: Admin1243%
  adminEmployeeFirstName: OrangeHRM
  adminEmployeeLastName: Admin
  workEmail: example.com
  contactNumber: ~

license:
  agree: y # y/n
